name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub (insecure)
      run: echo "LINUX5678" | docker login -u "LINUX478" --password-stdin

    - name: Build Docker image
      run: docker build -t LINUX478/my-python-app .

    - name: Push image to Docker Hub
      run: docker push LINUX478/my-python-app

